"""empty message

Revision ID: c96185b3634e
Revises: 8f4f8e6c4552
Create Date: 2026-03-03 12:44:15.740165

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c96185b3634e"
down_revision: Union[str, Sequence[str], None] = "8f4f8e6c4552"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cargo_types",
        sa.Column("catalogcode", sa.String(length=255), nullable=False),
        sa.Column("catalogname", sa.String(length=255), nullable=True),
        sa.Column("productname", sa.String(length=255), nullable=True),
        sa.Column("packagecode", sa.String(length=255), nullable=False),
        sa.Column("packagename", sa.String(length=255), nullable=True),
        sa.Column("is_count", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("catalogcode", name=op.f("pk_cargo_types")),
    )
    op.create_index(
        op.f("ix_cargo_types_catalogcode"), "cargo_types", ["catalogcode"], unique=True
    )
    op.create_index(
        op.f("ix_cargo_types_packagecode"), "cargo_types", ["packagecode"], unique=False
    )
    op.create_table(
        "quarries",
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_quarries")),
        sa.UniqueConstraint("name", name=op.f("uq_quarries_name")),
    )
    op.create_table(
        "cameras",
        sa.Column("quarry", sa.String(length=512), nullable=False),
        sa.Column("company_tin", sa.String(length=24), nullable=True),
        sa.Column("camera_path", sa.String(), nullable=False),
        sa.Column(
            "entry_car_position",
            sa.Enum("FORWARD", "BACKWARD", name="car_position_enum"),
            server_default=sa.text("'FORWARD'"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True, comment="Широта"),
        sa.Column("longitude", sa.Float(), nullable=True, comment="Долгота"),
        sa.ForeignKeyConstraint(
            ["company_tin"],
            ["companies.company_tin"],
            name=op.f("fk_cameras_company_tin_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["quarry"], ["quarries.name"], name=op.f("fk_cameras_quarry_quarries")
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_cameras")),
        sa.UniqueConstraint("name", name=op.f("uq_cameras_name")),
    )
    op.create_index(
        op.f("ix_cameras_camera_path"), "cameras", ["camera_path"], unique=True
    )
    op.add_column(
        "companies", sa.Column("quarry", sa.String(length=512), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_companies_quarry_quarries"),
        "companies",
        "quarries",
        ["quarry"],
        ["name"],
    )
    op.drop_column("companies", "quarry_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column("quarry_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_companies_quarry_quarries"), "companies", type_="foreignkey"
    )
    op.drop_column("companies", "quarry")
    op.drop_index(op.f("ix_cameras_camera_path"), table_name="cameras")
    op.drop_table("cameras")
    op.drop_table("quarries")
    op.drop_index(op.f("ix_cargo_types_packagecode"), table_name="cargo_types")
    op.drop_index(op.f("ix_cargo_types_catalogcode"), table_name="cargo_types")
    op.drop_table("cargo_types")
    # ### end Alembic commands ###
