"""empty message

Revision ID: 8f4f8e6c4552
Revises:
Create Date: 2026-03-03 11:22:19.986239

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f4f8e6c4552"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("quarry_id", sa.Integer(), nullable=False),
        sa.Column("company_tin", sa.String(length=24), nullable=False),
        sa.Column("short_name", sa.String(length=512), nullable=True),
        sa.Column("full_name", sa.String(length=1024), nullable=True),
        sa.Column("reg_date", sa.String(length=255), nullable=True),
        sa.Column("status_code", sa.String(length=50), nullable=True),
        sa.Column("status_name", sa.String(length=255), nullable=True),
        sa.Column("account", sa.String(length=255), nullable=True),
        sa.Column("bank_account", sa.String(length=255), nullable=True),
        sa.Column("bank_code", sa.String(length=255), nullable=True),
        sa.Column("mfo", sa.String(length=255), nullable=True),
        sa.Column("vat_code", sa.String(length=255), nullable=True),
        sa.Column("has_vat", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("director", sa.String(length=512), nullable=True),
        sa.Column("director_tin", sa.String(length=255), nullable=True),
        sa.Column("director_pinfl", sa.String(length=255), nullable=True),
        sa.Column("accountant", sa.String(length=512), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone_number", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True, comment="Широта"),
        sa.Column("longitude", sa.Float(), nullable=True, comment="Долгота"),
        sa.PrimaryKeyConstraint("company_tin", name=op.f("pk_companies")),
    )
    op.create_index(
        op.f("ix_companies_company_tin"), "companies", ["company_tin"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_company_tin"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
