"""empty message

Revision ID: 0787d33ad4d2
Revises: d008b7036dfa
Create Date: 2026-03-05 15:42:40.395093

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0787d33ad4d2"
down_revision: Union[str, Sequence[str], None] = "d008b7036dfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_cargo_types",
        sa.Column("catalogcode", sa.String(length=255), nullable=False),
    )
    op.drop_constraint(
        op.f("fk_company_cargo_types_cargo_type_id_cargo_types"),
        "company_cargo_types",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_company_cargo_types_catalogcode_cargo_types"),
        "company_cargo_types",
        "cargo_types",
        ["catalogcode"],
        ["catalogcode"],
    )
    op.drop_column("company_cargo_types", "cargo_type_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_cargo_types",
        sa.Column(
            "cargo_type_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_company_cargo_types_catalogcode_cargo_types"),
        "company_cargo_types",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_company_cargo_types_cargo_type_id_cargo_types"),
        "company_cargo_types",
        "cargo_types",
        ["cargo_type_id"],
        ["catalogcode"],
    )
    op.drop_column("company_cargo_types", "catalogcode")
    # ### end Alembic commands ###
