"""empty message

Revision ID: 5ecdeff91336
Revises: c96185b3634e
Create Date: 2026-03-03 13:48:52.114994

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ecdeff91336"
down_revision: Union[str, Sequence[str], None] = "c96185b3634e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_cameras_name"), "cameras", ["name"])
    op.add_column("companies", sa.Column("name", sa.String(length=512), nullable=True))
    op.create_unique_constraint(op.f("uq_quarries_name"), "quarries", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_quarries_name"), "quarries", type_="unique")
    op.drop_column("companies", "name")
    op.drop_constraint(op.f("uq_cameras_name"), "cameras", type_="unique")
    # ### end Alembic commands ###
