"""empty message

Revision ID: d008b7036dfa
Revises: cd5a0a4a5e29
Create Date: 2026-03-05 15:40:45.238856

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d008b7036dfa"
down_revision: Union[str, Sequence[str], None] = "cd5a0a4a5e29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_cargo_types",
        sa.Column("company_tin", sa.String(length=24), nullable=False),
        sa.Column("cargo_type_id", sa.String(length=255), nullable=False),
        sa.Column(
            "price_per_volume",
            sa.Numeric(precision=15, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cargo_type_id"],
            ["cargo_types.catalogcode"],
            name=op.f("fk_company_cargo_types_cargo_type_id_cargo_types"),
        ),
        sa.ForeignKeyConstraint(
            ["company_tin"],
            ["companies.company_tin"],
            name=op.f("fk_company_cargo_types_company_tin_companies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_cargo_types")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_cargo_types")
    # ### end Alembic commands ###
