"""empty message

Revision ID: cd5a0a4a5e29
Revises: 5ecdeff91336
Create Date: 2026-03-03 15:50:01.827615

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd5a0a4a5e29"
down_revision: Union[str, Sequence[str], None] = "5ecdeff91336"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cameras", sa.Column("camera_url", sa.Text(), nullable=True))
    op.add_column(
        "cameras",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "is_active")
    op.drop_column("cameras", "camera_url")
    # ### end Alembic commands ###
